import type { ArenaTraderModel } from "../types";

// CENTRAL BANK — 405B, highest capability tier, judges all traders
// Must be different provider family from any model it scores
export const CENTRAL_BANK_MODEL: ArenaTraderModel = {
  id: "nim-llama-3.1-405b-central",
  name: "LLAMA-3.1-405B [CENTRAL BANK]",
  provider: "nim",
  apiModel: "meta/llama-3.1-405b-instruct",
  balance: 0,
  startingBalance: 0,
  isInsolvent: false,
  isCentralBank: true,
  openPositions: [],
  loans: [],
  scores: {
    modelId: "nim-llama-3.1-405b-central",
    compositeScore: 0,
    pnlScore: 0,
    disciplineScore: 0,
    adaptabilityScore: 0,
    riskAppetiteScore: 0,
    lastEvaluatedAt: new Date().toISOString(),
  },
};

// TRADER MODELS — 10 unique models, no repeated weights across providers
// All ~70B class. Groq has only 2 distinct active 70B-class text models
// post-2025 deprecations, so NIM provides the remaining 8 slots.
export const TRADER_MODELS: ArenaTraderModel[] = [
  // ── GROQ ──────────────────────────────────────────────
  {
    id: "groq-llama-3.3-70b",
    name: "LLAMA-3.3-70B [GROQ]",
    provider: "groq",
    apiModel: "llama-3.3-70b-versatile",
    balance: 100,
    startingBalance: 100,
    isInsolvent: false,
    isCentralBank: false,
    openPositions: [],
    loans: [],
    scores: {
      modelId: "groq-llama-3.3-70b",
      compositeScore: 0,
      pnlScore: 0,
      disciplineScore: 0,
      adaptabilityScore: 0,
      riskAppetiteScore: 0,
      lastEvaluatedAt: new Date().toISOString(),
    },
  },
  {
    id: "groq-gpt-oss-120b",
    name: "GPT-OSS-120B [GROQ]",
    provider: "groq",
    apiModel: "openai/gpt-oss-120b",
    balance: 100,
    startingBalance: 100,
    isInsolvent: false,
    isCentralBank: false,
    openPositions: [],
    loans: [],
    scores: {
      modelId: "groq-gpt-oss-120b",
      compositeScore: 0,
      pnlScore: 0,
      disciplineScore: 0,
      adaptabilityScore: 0,
      riskAppetiteScore: 0,
      lastEvaluatedAt: new Date().toISOString(),
    },
  },
  // ── NIM ───────────────────────────────────────────────
  {
    id: "nim-llama-3.1-70b",
    name: "LLAMA-3.1-70B [NIM]",
    provider: "nim",
    apiModel: "meta/llama-3.1-70b-instruct",
    balance: 100,
    startingBalance: 100,
    isInsolvent: false,
    isCentralBank: false,
    openPositions: [],
    loans: [],
    scores: {
      modelId: "nim-llama-3.1-70b",
      compositeScore: 0,
      pnlScore: 0,
      disciplineScore: 0,
      adaptabilityScore: 0,
      riskAppetiteScore: 0,
      lastEvaluatedAt: new Date().toISOString(),
    },
  },
  {
    id: "nim-nemotron-70b",
    name: "NEMOTRON-70B [NIM]",
    provider: "nim",
    apiModel: "nvidia/llama-3.1-nemotron-70b-instruct",
    balance: 100,
    startingBalance: 100,
    isInsolvent: false,
    isCentralBank: false,
    openPositions: [],
    loans: [],
    scores: {
      modelId: "nim-nemotron-70b",
      compositeScore: 0,
      pnlScore: 0,
      disciplineScore: 0,
      adaptabilityScore: 0,
      riskAppetiteScore: 0,
      lastEvaluatedAt: new Date().toISOString(),
    },
  },
  {
    id: "nim-qwen2.5-72b",
    name: "QWEN2.5-72B [NIM]",
    provider: "nim",
    apiModel: "qwen/qwen2.5-72b-instruct",
    balance: 100,
    startingBalance: 100,
    isInsolvent: false,
    isCentralBank: false,
    openPositions: [],
    loans: [],
    scores: {
      modelId: "nim-qwen2.5-72b",
      compositeScore: 0,
      pnlScore: 0,
      disciplineScore: 0,
      adaptabilityScore: 0,
      riskAppetiteScore: 0,
      lastEvaluatedAt: new Date().toISOString(),
    },
  },
  {
    id: "nim-deepseek-r1-70b",
    name: "DEEPSEEK-R1-70B [NIM]",
    provider: "nim",
    apiModel: "deepseek-ai/deepseek-r1-distill-llama-70b",
    balance: 100,
    startingBalance: 100,
    isInsolvent: false,
    isCentralBank: false,
    openPositions: [],
    loans: [],
    scores: {
      modelId: "nim-deepseek-r1-70b",
      compositeScore: 0,
      pnlScore: 0,
      disciplineScore: 0,
      adaptabilityScore: 0,
      riskAppetiteScore: 0,
      lastEvaluatedAt: new Date().toISOString(),
    },
  },
  {
    id: "nim-llama-3.3-70b",
    name: "LLAMA-3.3-70B [NIM]",
    provider: "nim",
    apiModel: "meta/llama-3.3-70b-instruct",
    balance: 100,
    startingBalance: 100,
    isInsolvent: false,
    isCentralBank: false,
    openPositions: [],
    loans: [],
    scores: {
      modelId: "nim-llama-3.3-70b",
      compositeScore: 0,
      pnlScore: 0,
      disciplineScore: 0,
      adaptabilityScore: 0,
      riskAppetiteScore: 0,
      lastEvaluatedAt: new Date().toISOString(),
    },
  },
  {
    id: "nim-llama-3.2-90b",
    name: "LLAMA-3.2-90B [NIM]",
    provider: "nim",
    apiModel: "meta/llama-3.2-90b-vision-instruct",
    balance: 100,
    startingBalance: 100,
    isInsolvent: false,
    isCentralBank: false,
    openPositions: [],
    loans: [],
    scores: {
      modelId: "nim-llama-3.2-90b",
      compositeScore: 0,
      pnlScore: 0,
      disciplineScore: 0,
      adaptabilityScore: 0,
      riskAppetiteScore: 0,
      lastEvaluatedAt: new Date().toISOString(),
    },
  },
  {
    id: "nim-mistral-nemo-12b",
    name: "MISTRAL-NEMO-12B [NIM]",
    provider: "nim",
    apiModel: "mistralai/mistral-nemo-12b-instruct",
    balance: 100,
    startingBalance: 100,
    isInsolvent: false,
    isCentralBank: false,
    openPositions: [],
    loans: [],
    scores: {
      modelId: "nim-mistral-nemo-12b",
      compositeScore: 0,
      pnlScore: 0,
      disciplineScore: 0,
      adaptabilityScore: 0,
      riskAppetiteScore: 0,
      lastEvaluatedAt: new Date().toISOString(),
    },
  },
  {
    id: "nim-phi-3-medium-14b",
    name: "PHI-3-MEDIUM-14B [NIM]",
    provider: "nim",
    apiModel: "microsoft/phi-3-medium-4k-instruct",
    balance: 100,
    startingBalance: 100,
    isInsolvent: false,
    isCentralBank: false,
    openPositions: [],
    loans: [],
    scores: {
      modelId: "nim-phi-3-medium-14b",
      compositeScore: 0,
      pnlScore: 0,
      disciplineScore: 0,
      adaptabilityScore: 0,
      riskAppetiteScore: 0,
      lastEvaluatedAt: new Date().toISOString(),
    },
  },
];

export const getAllModels = () => [...TRADER_MODELS, CENTRAL_BANK_MODEL];
export const getModelById = (id: string): ArenaTraderModel | null =>
  getAllModels().find((m) => m.id === id) ?? null;
export const getTraderById = (id: string): ArenaTraderModel | null =>
  TRADER_MODELS.find((m) => m.id === id) ?? null;
